# **Train Test Split**

**Import the relevant libraries**

In [1]:
import numpy as np 
from sklearn.model_selection import train_test_split

**Generate data to split**

In [2]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

**Split the data**

**train_test_split(x)** splits arrays or matrices into random train and test subsets

In [4]:
train_test_split(a)

[array([ 94,   1,  22,  11,  48,  58,  14,  77,  67,  56,  50, 100,  86,
         35,  92,  47,  81,  46,  98,  31,  65,  69,   8,  27,  52,  60,
         88,   9,  82,  15,  18,  44,  59,  96,  57,  89,  73,   5,  75,
         63,  74,  51,  29,  71,  93,  32,  13,  87,  68,  16,  30,  20,
         21,  85,  54,   7,  10,  76,  84,  45,  95,  62,  97,  99,  49,
         61,   4,  37,   3,  26,  36,   2,  70,  24,  43]),
 array([25, 41, 23, 42, 72, 28, 19, 33, 34, 80, 90, 40, 55, 83, 79, 78,  6,
        91, 17, 39, 53, 66, 12, 64, 38])]

In [5]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, random_state = 42)

#a_train, a_test = train_test_split(a, test_size=0.2,shuffle=False)

**train_test_split(x,y)** splits arrayS or matriceS into random train and test subsets

**test_size** = 0.2 will split the data in 80% and 20%

**shuffle** = False will maintain the sequence if we don't mention this it is randomly shuffled everytime we run the code

**random_state** = 42 to have the same random values each time

**Explore the result**

In [6]:
a_train.shape, a_test.shape

((80,), (20,))

In [7]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [8]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [9]:
b_train.shape, b_test.shape

((80,), (20,))

In [10]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [11]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])

As observed both a and b are shuffles in same way.